apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot2-may1-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/chatbot2-may1-2:7bffa554402bc92c1507bb4bac50b6963524cfe1@sha256:6b2b41bf94d377ea2b2ccf83c11181579fede5568d6f733fa1f14abff0a3dcc8 # use pre-built to bootstrap
          name: app-inference
